name: Unity CI

on:
  push:
    branches: [ main_devops ]
  pull_request:
    branches: [ master ]

jobs:
  setupUnity:
    strategy:
      matrix:
        unity: ["2019.3.6f1"]
        include:
          - unity: 2019.3.6f1
            license: UNITY_LICENSE_2019
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v2
          with:
            lfs: true

        - name: Get Unity Licence
          run: |
            echo ::set-env name=UNITY_LICENSE::$(openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf)
          
        - name: Build UnitTest(Linux64, mono)
          uses: game-ci/unity-builder@v2.0-alpha-6
          with:
            projectPath: RuntimeUnitTestToolkit
            unityVersion: ${{ matrix.unity }}
            targetPlatform: StandaloneLinux64
            buildMethod: UnitTestBuilder.BuildUnitTest
            customParameters: /headless /ScriptBackend Mono2x
            versioning: None
        - name: Execute UnitTest
          run: ./RuntimeUnitTestToolkit/bin/UnitTest/StandaloneLinux64_Mono2x/test

        # Execute scripts: Export Package
        # /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod PackageExporter.Export
        - name: Export unitypackage
          uses: game-ci/unity-builder@v2.0-alpha-6
          with:
            projectPath: RuntimeUnitTestToolkit
            unityVersion: ${{ matrix.unity }}
            targetPlatform: StandaloneLinux64
            buildMethod: PackageExporter.Export
            versioning: None
            
  buildApk:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.6f1
    steps:
        # Build Windows and OSX
        - name: Build Windows Player
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildWindows64Player ./bin-win64/CISample.exe
        - name: Build OSX Player
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -buildOSXUniversalPlayer ./bin-osx/CISample.app      
        
        - name: Archive Windows Build
          uses: actions/upload-artifact@v1
          with:
            name: CISampleWin64Binary
            path: ./bin-win64

        - name: Archive Mac Build
          uses: actions/upload-artifact@v1
          with:
            name: CISampleOSXBinary
            path: ./bin-osx
